services:
    php:
        build: ./
        volumes:
            - ./:/var/www/
        depends_on:
            - pgsql

    cli:
        build: ./
        volumes:
            - ./:/var/www/
        depends_on:
            - pgsql
        user: 1000:1000
        tty: true

    nginx:
        image: nginx:stable-alpine
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - pgsql
            - php

    pgsql:
        image: postgres:17-alpine
        restart: unless-stopped
        environment:
            POSTGRES_DB: "brick"
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "password"
        ports:
            - "5432:5432"
        volumes:
            - db_data_brick:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U admin -d brick"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 4G

    node:
        image: node:20-alpine
        ports:
            - "3000:3000"
        volumes:
            - ./:/var/www/
        working_dir: /var/www/
        tty: true

volumes:
    db_data_brick:
